---
services:
  migrate-generator:
    build:
      context: "./migrate"
      target: "generate-template"
    container_name: "migrate-generator"

  migrate-up:
    build:
      context: "./migrate"
      target: "migration"
    container_name: "migrate-up"
    environment:
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT_INTERNAL}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      TZ: "${TZ}"

  migrate-down:
    build:
      context: "./migrate"
      target: "migration"
    container_name: "migrate-down"
    environment:
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT_INTERNAL}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      TZ: "${TZ}"
